/**
 * @file components/core/include/command_types.h
 * @brief System command identifiers – atomic actions issued by the core.
 *
 * =============================================================================
 * ARCHITECTURAL ROLE
 * =============================================================================
 * Defines the complete set of executable actions that the system can perform.
 * Commands represent intent, not data or decisions.
 *
 * - Each command ID is stable and unique.
 * - Commands are generated by state_manager during transitions.
 * - They are dispatched via command_router to the appropriate service handler.
 *
 * =============================================================================
 * DESIGN PRINCIPLES
 * =============================================================================
 * - No data attached (parameters are in command_params.h)
 * - No logic or interpretation
 * - Grouped by functional domain for readability
 * - CMD_COUNT is always the last enumerator
 *
 * =============================================================================
 * USAGE
 * =============================================================================
 * This enumeration is used by:
 * - state_manager (to decide which commands to issue)
 * - command_router (to index handler registry)
 * - services (to identify which command they are handling)
 *
 * =============================================================================
 * @author matthithyahu
 * @date 2026
 */

#ifndef COMMAND_TYPES_H
#define COMMAND_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Command identifiers.
 */
typedef enum
{
    /* --------------------------------------------------------
     * System control
     * -------------------------------------------------------- */
    COMMAND_NONE = 0,               /**< No operation (reserved) */
    COMMAND_SYSTEM_ARM,             /**< Arm system for flight */
    COMMAND_SYSTEM_DISARM,          /**< Disarm system */
    COMMAND_ABORT_MISSION,          /**< Immediate mission abort */

    /* --------------------------------------------------------
     * Flight control (gimbal / TVC) – Quaternion primary
     * -------------------------------------------------------- */
    COMMAND_SET_GIMBAL_QUATERNION,  /**< Set gimbal orientation using quaternion (primary) */
    COMMAND_SET_GIMBAL_ANGLES,      /**< Set orientation using Euler angles (fallback/debug) */
    COMMAND_ENABLE_GIMBAL_CONTROL,  /**< Start active gimbal control */
    COMMAND_STOP_GIMBAL_CONTROL,    /**< Stop gimbal control */

    /* --------------------------------------------------------
     * Recovery system (parachute)
     * -------------------------------------------------------- */
    COMMAND_ARM_PARACHUTE,          /**< Enable parachute system */
    COMMAND_DISARM_PARACHUTE,       /**< Disable parachute system */
    COMMAND_DEPLOY_PARACHUTE,       /**< Trigger parachute deployment */

    /* --------------------------------------------------------
     * Telemetry
     * -------------------------------------------------------- */
    COMMAND_START_TELEMETRY,        /**< Start telemetry streaming */
    COMMAND_STOP_TELEMETRY,         /**< Stop telemetry */
    COMMAND_SEND_TELEMETRY,         /**< Send single telemetry packet */

    /* --------------------------------------------------------
     * WiFi commands
     * -------------------------------------------------------- */
    COMMAND_CONNECT_WIFI,           /**< Connect to a WiFi access point */
    COMMAND_DISCONNECT_WIFI,        /**< Disconnect from WiFi */
    COMMAND_SET_CONFIG_WIFI,        /**< Set WiFi configuration (retry, etc.) */
    COMMAND_SCAN_WIFI,              /**< Perform a WiFi scan */
    COMMAND_GET_STATUS_WIFI,        /**< Query current WiFi status */

    /* --------------------------------------------------------
     * MQTT commands
     * -------------------------------------------------------- */
    COMMAND_CONNECT_MQTT,           /**< Connect to MQTT broker */
    COMMAND_DISCONNECT_MQTT,        /**< Disconnect from MQTT broker */
    COMMAND_SET_CONFIG_MQTT,        /**< Set MQTT configuration */
    COMMAND_PUBLISH_MQTT,           /**< Publish a message */
    COMMAND_SUBSCRIBE_MQTT,         /**< Subscribe to a topic */
    COMMAND_UNSUBSCRIBE_MQTT,       /**< Unsubscribe from a topic */
    COMMAND_MQTT_SET_WIFI_STATE,    /**< Inform MQTT service about WiFi state */

    /* --------------------------------------------------------
     * GPS commands
     * -------------------------------------------------------- */
    COMMAND_GPS_START,              /**< Start GPS module */
    COMMAND_GPS_STOP,               /**< Stop GPS module */
    COMMAND_GPS_GET_LAST_FIX,       /**< Get last GPS fix */

    /* --------------------------------------------------------
     * Timer services
     * -------------------------------------------------------- */
    COMMAND_START_TIMER,            /**< Start a one-shot timer */
    COMMAND_STOP_TIMER,             /**< Stop a running timer */
    COMMAND_START_PERIODIC_TIMER,   /**< Start a periodic timer */
    COMMAND_STOP_PERIODIC_TIMER,    /**< Stop a periodic timer */

    /* --------------------------------------------------------
     * Payload (camera)
     * -------------------------------------------------------- */
    COMMAND_START_RECORDING,        /**< Start video recording */
    COMMAND_STOP_RECORDING,         /**< Stop video recording */
    COMMAND_CAPTURE_IMAGE,          /**< Capture still image */

    /* --------------------------------------------------------
     * Logging / storage
     * -------------------------------------------------------- */
    COMMAND_START_LOGGING,          /**< Start data logging */
    COMMAND_STOP_LOGGING,           /**< Stop data logging */
    COMMAND_FLUSH_STORAGE,          /**< Flush buffered data */

    COMMAND_LOG_MESSAGE,            /**< Log a message (params: log_message_params_t) */

    /* --------------------------------------------------------
     * Sentinel – must be last
     * -------------------------------------------------------- */
    COMMAND_COUNT

} command_type_t;

#ifdef __cplusplus
}
#endif

#endif /* COMMAND_TYPES_H */